version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_STATIC_ROOT=/var/www/zamda/backend/staticfiles
      - DJANGO_MEDIA_ROOT=/var/www/zamda/backend/media

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://zamda.com
